version: '3.8'
services:
  chainlink-node:
    container_name: chainlink
    command: local node -p /chainlink/.password -a /chainlink/.api
    volumes:
      - ./:/chainlink
    image: smartcontract/chainlink:1.1.1
    restart: on-failure
    depends_on:
      - db
    ports:
      - 6688:6688
    links:
      - db
    environment:
      ROOT: /chainlink
      LOG_LEVEL: debug
      ETH_CHAIN_ID: 1337
      CHAINLINK_TLS_PORT: 0
      SECURE_COOKIES: "false"
      ALLOW_ORIGINS: "*"
      ETH_URL: ws://host.docker.internal:8545
      # DATABASE_URL: postgresql://postgres:linklink@35.223.226.69:5432/postgres
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    # volumes:
    #   - db:/var/lib/postgresql/data

# volumes:
#   db:
#     driver: local
